//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirectOrderTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustPO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustPO()
        {
            this.CustPOLines = new HashSet<CustPOLine>();
        }
    
        public int CustPOID { get; set; }
        public string POShipToRef { get; set; }
        public string POComment { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> DocsSent { get; set; }
        public Nullable<bool> DocsReceived { get; set; }
        public Nullable<bool> DeliveredToCust { get; set; }
        public Nullable<bool> ShippedInSystem { get; set; }
        public Nullable<int> LinkFreightPOID { get; set; }
        public Nullable<int> CarrId { get; set; }
        public string SalesOrder { get; set; }
        public string PriorPOCode { get; set; }
        public string PPROREFDATE { get; set; }
        public Nullable<byte> POStatusID { get; set; }
        public string ApptNum { get; set; }
        public Nullable<bool> POAlert { get; set; }
        public string POBillToRef { get; set; }
        public Nullable<bool> ReceivedPPRO { get; set; }
        public Nullable<bool> ReceivedFoodLink { get; set; }
        public string ReroutePOCustCode { get; set; }
        public Nullable<short> CustBillToID { get; set; }
        public Nullable<short> CustShipToID { get; set; }
        public Nullable<byte> CompanyID { get; set; }
        public string ReroutePOCode { get; set; }
        public Nullable<short> PriorPOCustCode { get; set; }
        public Nullable<bool> Reroute { get; set; }
        public string SalesOrderAlt { get; set; }
        public Nullable<byte> AlertReasonID { get; set; }
        public Nullable<int> LoadID { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<decimal> POGM { get; set; }
        public string MainCommodity { get; set; }
        public Nullable<decimal> POFrghtRate { get; set; }
        public string POFreightLinkToCode { get; set; }
        public string trip { get; set; }
        public string LogisticsPO { get; set; }
        public string ConfNum { get; set; }
        public string EVNum { get; set; }
        public Nullable<byte> StopNum { get; set; }
        public Nullable<System.DateTime> BOLRequestSent { get; set; }
        public Nullable<System.DateTime> DeliveryRequestSent { get; set; }
        public Nullable<System.DateTime> TruckingArrivalDate { get; set; }
        public Nullable<int> POLoadStatusID { get; set; }
        public string SOURCE { get; set; }
        public string TYPE { get; set; }
        public string LOT { get; set; }
        public string SUBLOT { get; set; }
        public string CONDCODE { get; set; }
        public string WAREHOUSE { get; set; }
        public Nullable<decimal> LINE { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public string PPROCREATEDATE { get; set; }
        public string PPROCREATETIME { get; set; }
        public Nullable<int> PRODID { get; set; }
        public Nullable<decimal> UNITPRICE { get; set; }
        public Nullable<decimal> UNITCOST { get; set; }
        public string REFSTATUS { get; set; }
        public string Comment { get; set; }
        public Nullable<decimal> AltQty { get; set; }
        public Nullable<System.DateTime> LASTBULKUPDATE { get; set; }
        public string PPROMODDATE { get; set; }
        public string PPROMODTIME { get; set; }
        public string Salesperson { get; set; }
        public Nullable<System.DateTime> LoadDate { get; set; }
        public Nullable<System.DateTime> ArrivalDate { get; set; }
        public Nullable<int> VendId { get; set; }
        public string VendorPO { get; set; }
    
        public virtual Carrier Carrier { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Customer Customer1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustPOLine> CustPOLines { get; set; }
        public virtual Product Product { get; set; }
        public virtual POStatu POStatu { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
