//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirectOrderTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustPOLine
    {
        public int CustPOLineID { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Comment { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string Origin { get; set; }
        public Nullable<System.DateTime> POLineLoadDate { get; set; }
        public string ApptNum { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string VendRefNum { get; set; }
        public Nullable<byte> POLineStatusID { get; set; }
        public Nullable<int> ProdID { get; set; }
        public string FreshouseRefNum { get; set; }
        public Nullable<int> VendId { get; set; }
        public string VendRefNumAlt { get; set; }
        public Nullable<decimal> MiscCharge { get; set; }
        public Nullable<decimal> PHDSCharge { get; set; }
        public Nullable<decimal> VBRCharge { get; set; }
        public Nullable<decimal> CostAlt { get; set; }
        public string VendAlt { get; set; }
        public Nullable<byte> ChargeTypeID { get; set; }
        public Nullable<decimal> LineGM { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<byte> AlertReasonID { get; set; }
        public string ModifiedBy { get; set; }
        public string CreatedBy { get; set; }
        public string VendPurchPONum { get; set; }
        public Nullable<int> CustPOID { get; set; }
        public Nullable<decimal> LineFrghtRate { get; set; }
        public Nullable<decimal> MiscChargePerPc { get; set; }
        public Nullable<byte> PerPcChargeTypeID { get; set; }
        public Nullable<short> ShipperId { get; set; }
        public string Pickup { get; set; }
        public Nullable<decimal> PalletCount { get; set; }
        public Nullable<bool> ActionRequired { get; set; }
        public Nullable<bool> Booked { get; set; }
        public Nullable<bool> Manifest { get; set; }
        public Nullable<bool> ConfirmQty { get; set; }
        public string LOT { get; set; }
        public string PPROREFDATE { get; set; }
        public Nullable<System.DateTime> LASTBULKUPDATE { get; set; }
        public string SOURCE { get; set; }
        public string TYPE { get; set; }
        public string CONDCODE { get; set; }
        public string SUBLOT { get; set; }
        public Nullable<decimal> LINE { get; set; }
        public string WAREHOUSE { get; set; }
        public string PPROCREATETIME { get; set; }
        public string PPROCREATEDATE { get; set; }
        public string PPROMODDATE { get; set; }
        public string PPROMODTIME { get; set; }
        public Nullable<decimal> AltQty { get; set; }
        public string POLineComment { get; set; }
        public string LoadNumber { get; set; }
        public string CarrierCode { get; set; }
        public string CarrierDesc { get; set; }
        public string Buyer { get; set; }
        public Nullable<System.DateTime> REFDATESQL { get; set; }
    
        public virtual CustPO CustPO { get; set; }
        public virtual Product Product { get; set; }
        public virtual Vendor Vendor { get; set; }
        public virtual POLineStatu POLineStatu { get; set; }
    }
}
