//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirectOrderTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.CustPOes = new HashSet<CustPO>();
            this.CustPOLines = new HashSet<CustPOLine>();
            this.ProdCats = new HashSet<ProdCat>();
        }
    
        public int ProdID { get; set; }
        public string ProdNum { get; set; }
        public string ProdCode { get; set; }
        public string ProdDesc { get; set; }
        public string ProdAltDesc { get; set; }
        public Nullable<short> ProdSize { get; set; }
        public string ProdCountPer { get; set; }
        public Nullable<int> ProdWeight { get; set; }
        public string ProdGrade { get; set; }
        public string ProdPack { get; set; }
        public string Commodity { get; set; }
        public string ProductType { get; set; }
        public byte ProdCompany { get; set; }
        public Nullable<short> CasesPerPallet { get; set; }
        public Nullable<decimal> RepackRatio { get; set; }
        public Nullable<decimal> ReorderAdviseQuant { get; set; }
        public Nullable<decimal> ReorderQuant { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustPO> CustPOes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustPOLine> CustPOLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProdCat> ProdCats { get; set; }
    }
}
