//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirectOrderTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdCat
    {
        public int ProdCatID { get; set; }
        public int Prodid { get; set; }
        public short CategoryID { get; set; }
        public bool Invisible { get; set; }
        public Nullable<short> SortOrder { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
